# Generated by Django 3.0.6 on 2020-05-14 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='users',
            field=models.ManyToManyField(related_name='shops', to=settings.AUTH_USER_MODEL),
        ),
    ]
